package com.iobits.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single row in the 'users' table.
 *
 * @property id The unique identifier for the user. Auto-generated by Room.
 * @property name The name of the user.
 * @property email The email address of the user.
 */
@Entity(tableName = "users")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val email: String
)